name: Tashimasu Push Update

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.TSMS_KEY }}
        known_hosts: ${{ secrets.TSMS_KNOWN_HOSTS }}
        
    - name: Checkout the Repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.TSMS_KEY }}
        fetch-depth: 0
        ref: master
    - name: Push to Tashimasu
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add prod ssh://git@git.tashimasu.net:vol/test.git
        git push prod        
